[workspace]
resolver = "3"
members = [
    "app",
    "screen_grid"
]

[workspace.dependencies]
wgpu = "25.0"
screen_grid = { path = "screen_grid" }
bitflags = "2.9.1"
env_logger = "0.11.8"
log = "0.4.27"

