[package]
name = "screen_grid"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
env_logger = { workspace = true } 
log = { workspace = true } 
glyphon = { workspace = true }
